//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourfirmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroup
    {
        public int Group_ID { get; set; }
        public int Customer_ID { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string DocumentType { get; set; }
        public string DocumentData { get; set; }
        public System.DateTime BirthdayDate { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
