//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourfirmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsPhoto
    {
        public string Photo { get; set; }
        public int HotelID { get; set; }
        public int ID { get; set; }
    
        public virtual Hotels Hotels { get; set; }
    }
}
