//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourfirmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int TourID { get; set; }
        public int EmploeerID { get; set; }
        public decimal DealAmount { get; set; }
        public Nullable<decimal> Prepayment { get; set; }
        public string PaymentState { get; set; }
        public string OrderState { get; set; }
        public System.DateTime ConclusionDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
