//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourfirmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tours()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int TourID { get; set; }
        public int HotelID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string RoomCategory { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaximumAmount { get; set; }
        public int VacantPremises { get; set; }
        public decimal CostForTwo { get; set; }
        public decimal CostForOne { get; set; }
        public decimal ExtraBed { get; set; }
        public string Nutrition { get; set; }
        public int AccruedBonus { get; set; }
    
        public virtual Hotels Hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
